Added all, network, permissions modifiers
AdguardTeam/AGLint pull request #165
Opened 2023-06-15 17:35 UTC by jellizaveta

The network modifier only corresponds to IP addresses and supports regexp. I made a regexp against these two criteria, but regexp should also point to an ip address, should this be taken into some way?

2023-06-15 21:36 UTC, scripthunter7 requested changes
Please add TODO comments, see my suggestions

2023-06-15 21:36 UTC, scripthunter7 commented on src/compatibility-tables/modifiers/network.yml
> +  # value_format: /^(?:\d{1,3}\.){3}\d{1,3}(?::\d+)?$|^\[?[0-9a-fA-F:]+\]?(?::\d+)?$|^\/(?:[^\/\\]|\\.)*\/[a-z]*$/
```suggestion
  # TODO: Implement validation
  # value_format: /^(?:\d{1,3}\.){3}\d{1,3}(?::\d+)?$|^\[?[0-9a-fA-F:]+\]?(?::\d+)?$|^\/(?:[^\/\\]|\\.)*\/[a-z]*$/
```

2023-06-15 21:51 UTC, scripthunter7 commented on src/compatibility-tables/modifiers/permissions.yml
> +  # value_format:
@jellizaveta `value_format` always refers to the value assigned to the modifier in the following form: `$modifier=assigned_value`

There is currently no planned field in the compatibility table for checking the pattern before the modifier list

2023-06-15 21:52 UTC, scripthunter7 commented on src/compatibility-tables/modifiers/permissions.yml
> +  # value_format:
cc @slavaleleka

2023-06-15 21:56 UTC, scripthunter7 commented on src/compatibility-tables/modifiers/network.yml
> +  # value_format: /^(?:\d{1,3}\.){3}\d{1,3}(?::\d+)?$|^\[?[0-9a-fA-F:]+\]?(?::\d+)?$|^\/(?:[^\/\\]|\\.)*\/[a-z]*$/
@jellizaveta `value_format` always refers to the value assigned to the modifier in the following form: `$modifier=assigned_value`

There is currently no planned field in the compatibility table for checking the pattern before the modifier list

CC @slavaleleka

2023-06-15 21:58 UTC, scripthunter7 requested changes

2023-06-15 21:58 UTC, scripthunter7 commented on src/compatibility-tables/modifiers/permissions.yml
> +  docs: https://adguard.com/kb/general/ad-filtering/create-own-filters/#network-modifier
```suggestion
  docs: https://adguard.com/kb/general/ad-filtering/create-own-filters/#permissions-modifier
```

2023-06-16 09:10 UTC, Alex-302 approved these changes

2023-06-16 09:13 UTC, zloyden approved these changes

2023-06-16 09:24 UTC, scripthunter7 approved these changes
LGTM, but please wait for @slavaleleka

2023-06-16 09:30 UTC, slavaleleka approved these changes

2023-06-16 09:44 UTC, merged